# Generated by Django 4.0.6 on 2022-10-25 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamer', '0001_initial'),
        ('nofilter', '0003_alter_userpostlikes_table_delete_postrating'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nofilter_highschool_rating',
            name='nofilter_highschool_id',
        ),
        migrations.RemoveField(
            model_name='nofilter_user_info',
            name='nofilter_highschool',
        ),
        migrations.RemoveField(
            model_name='nofilter_user_info',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mbti_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='dreamer.mbti'),
        ),
        migrations.AddField(
            model_name='user',
            name='sns_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Nofilter_highschool',
        ),
        migrations.DeleteModel(
            name='Nofilter_highschool_rating',
        ),
        migrations.DeleteModel(
            name='Nofilter_user_info',
        ),
    ]
