# Generated by Django 4.0.6 on 2022-10-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_country_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country_id',
            new_name='country',
        ),
    ]
