# Generated by Django 4.0.6 on 2022-10-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_country_id_user_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
