# Generated by Django 4.0.6 on 2022-10-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nofilter', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpostlikes',
            table='User_Post_Likes',
        ),
        migrations.DeleteModel(
            name='PostRating',
        ),
    ]
